package com.ifts.aula_virtual_backend.persistence.entity;

public enum AcademicPlanEnum
{
    TECNICO_SUPERIOR_EN_ANALISIS_DE_SISTEMAS,
    TECNICO_SUPERIOR_EN_ANALISIS_DE_SISTEMAS_VIEJO_PLAN,
    TECNICO_SUPERIOR_EN_ADMINISTRACION_PUBLICA_CON_ORIENTACION_MUNICIPAL
}
